apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-deployment-guard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-deployment-guard
  template:
    metadata:
      labels:
        app: smart-deployment-guard
    spec:
      containers:
        - name: smart-deployment-guard
          image: smart-deployment-guard:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5